### ISSUE TITLE
Number problems

### ISSUE THREAD

**Issue by Hughp135** [geckosio/typed-array-buffer-schema#1]
This might be my lack of understanding of array buffers etc, but I'm struggling to get a schema that works consistently for numbers with decimal points.

I have tried with int32 and float32s, with `digits` set to 4.

However, when using int32, certain values cause subsequent objects in the state to not encode/decode correctly.

To explain my intention, I want to be able to send number coordinates within a range of about -60k to +60k, with accuracy to at least 2 decimal places, but 4 ideally.

Example of failing test:

```
describe('stuff', () => {
  it('decodes state correctly', () => {
    // Note: in the schema, x is an int32 with 4 digits
    const gameState: GameState = {
      players: [
        { id: '1', x: 0.9 },
        { id: '2', x: -4.475 },
      ]
    }

    const buffer = mainModel.toBuffer(gameState);
    const decoded = mainModel.fromBuffer(buffer);

    expect(decoded.players[0].x).toEqual(0.9); // passes
    expect(decoded.players[1]).toBeDefined(); // fails
  })
})
```

If x is 0.93, 1, or most other values, it works and both players are decoded correctly, but not if you set it to 0.91 or 0.92.

In the case where the test fails, player 1 is decoded correctly, but player 2 doesn't exist at all.

I find this very confusing - it seems to work more consistently with `float32` instead of `int32`, but then with floats, the numbers don't always round accurately. Do you have any advice to use for this situation?

**Comment by yandeu** [comment]
Can you please share your model?

**Comment by Hughp135** [comment]
Hi, this is the full schema I used (only showed 'x' in my example above to simplify the code).

```
const playerSchema = BufferSchema.schema('player', {
  id: { type: string8, length: 16 },
  name: { type: string8, length: 16 },
  x: { type: int32, digits: 4 },
  y: { type: int32, digits: 4 },
  z: { type: int32, digits: 4 },
  rot: { type: int32, digits: 4 },
});

export const mainSchema = BufferSchema.schema('snapshot', {
  players: [playerSchema],
});

export const mainModel = new Model(mainSchema);
```

**Comment by yandeu** [comment]
This was clearly a bug. I have fixed it in da0a0f62db0bd10262361698a4b3f5c92d8cbc70. I will publish it to npm within the next minutes. 

Can you test it and give me a feedback?

**Comment by Hughp135** [comment]
Hi, can confirm my cases are fixed now! thanks for the update.

**Comment by yandeu** [comment]
You're welcome :)
