### ISSUE TITLE
Property named `type` breaks `fromBuffer`

### ISSUE THREAD

**Issue by x89-h** [geckosio/typed-array-buffer-schema#12]
**Describe the bug**
I have been using this successfully in my project for about a week. Yesterday I decided to add some more data to my main `gameState` schema. My data looked like this:

```js
{
  time: 1234567890
  objects: [ {
    id: 0,
    type: 2,
    health: 82
  } ]
}
```

My schema looked like this:
```js
// gameState Schema
{
  time: int64,
  objects: [ objectSchema ]
}

// objectSchema
{
  id: uint8,
  type: uint8,
  health: uint8
}
```

It encoded without error, but it did not decode correctly. It would decode as an `objects` array with three members (I realized this number always had a direct correlation to the number of properties in `objectSchema`). After hours of debugging and trying a lot of things, I found that renaming `type` to something else (ex: `objectType`) fixed this problem. I believe this has something to do with how the schema is read (looking for a `type` property). It would be nice if this were fixed (I realize it may not be possible), or at least a warning provided in `README.md` to help future people.

If this has been unclear, I am sorry. Here is a visual example of what I would get decoding the data above (random numbers added, because I didn't record the actual result):

```js
{
  time: 1234567890
  objects: [
    {
      id: 0,
      type: 2,
      health: 82
    },
    {
      id: 63,
      type: 21,
      health: 43.2
    },
    {
      id: 86,
      type: 142.8,
      health: 13
    }
  ]
}
```

This issue is easily reproducible.

**Comment by yandeu** [comment]
Thanks for reporting. I will check it.

**Comment by yandeu** [comment]
Yes, `type`, `digits` and `lenght` are keys for internal use. I am not sure if there is an easy fix or if we should just write it to the docs.

Would you mind testing all of these keywords and adding it to the docs?

**Comment by x89-h** [comment]
I would not mind. I will do that tomorrow afternoon.

**Comment by x89-h** [comment]
This could be fixable, if one checks to make sure the object that includes `type`, `digits`, and `length` only includes `type`, `digits`, and `length`. I will try this as well.
