### ISSUE TITLE
RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by KingCosmic** [geckosio/typed-array-buffer-schema#17]
**Describe the bug**
After around 120 people join I recieve this error.

```
file:///C:/Users/KingCosmic/Desktop/work/AtlantisCity-Server/dist/server.js:253
        finally { if (e_2) throw e_2.error; }
                           ^

RangeError: Offset is outside the bounds of the DataView
    at DataView.setUint8 (<anonymous>)
    at C:\Users\KingCosmic\Desktop\work\AtlantisCity-Server\node_modules\@geckos.io\typed-array-buffer-schema\lib\serialize.js:93:36
    at Array.forEach (<anonymous>)
    at Model.toBuffer (C:\Users\KingCosmic\Desktop\work\AtlantisCity-Server\node_modules\@geckos.io\typed-array-buffer-schema\lib\serialize.js:90:14)
    at Terrain.value (file:///C:/Users/KingCosmic/Desktop/work/AtlantisCity-Server/dist/systems/terrain/index.js:254:44)
    at World.value (file:///C:/Users/KingCosmic/Desktop/work/AtlantisCity-Server/dist/systems/world.js:492:26)
    at Timeout._onTimeout (file:///C:/Users/KingCosmic/Desktop/work/AtlantisCity-Server/dist/server.js:245:19)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

I don't use a Uint8 specifically os unsure why `DataView.setUint8` would be where it crashes but maybe I'm missing something.

my models are as follow.
```js
import { BufferSchema, Model } from '@geckos.io/typed-array-buffer-schema'
import { int64, string8, uint64 } from '@geckos.io/typed-array-buffer-schema'

const newPlayer = BufferSchema.schema('newPlayer', {
  id: { type: string8, length: 24 },
  username: { type: string8, length: 14 },
  x: { type: int64, digits: 4 },
  y: { type: int64, digits: 4 },
  animation: { type: string8, length: 2 },
  direction: { type: string8, length: 2 }
})

const updatedPlayer = BufferSchema.schema('updatedPlayer', {
  id: { type: string8, length: 24 },
  username: { type: string8, length: 14 },
  x: { type: int64, digits: 4 },
  y: { type: int64, digits: 4 },
  animation: { type: string8, length: 2 },
  direction: { type: string8, length: 2 }
})

const removedPlayer = BufferSchema.schema('removedPlayer', {
  id: { type: string8, length: 24 }
})

const mainSchema = BufferSchema.schema('main', {
  id: { type: string8, length: 6 },
  time: uint64,
  state: {
    isn: int64,
    newEntities: [newPlayer],
    updatedEntities: [updatedPlayer],
    removedEntities: [removedPlayer]
  }
})

export const mainModel = new Model(mainSchema)
```

I'm assuming I did something wrong as per my last issue where i didn't realize there couldnt be duplicate models. so hopefully this is as simple.

**Comment by Jalcantara88** [comment]
I have also run into this particular predicament. Would love some insight on the issue. 

Thank You

**Comment by Codezilluh** [comment]
It is probably a bug with `string8`. I will check it out today.

On a separate note, I wouldn't recommend serializing your IDs as 24 byte strings. You should try using integers as your IDs and saving them in a `uint8` (1 byte; 255 UIDs) or `uint16` (2 bytes; 65535 UIDs), depending on how many unique IDs you need.

**Comment by KingCosmic** [comment]
I'm just using the geckos built in id for the moment but if I can swap that to uint that would be lovely

**Comment by Codezilluh** [comment]
> I'm just using the geckos built in id for the moment but if I can swap that to uint that would be lovely

I would make a lookup object for the ids

**Comment by KingCosmic** [comment]
if it is a string8 bug any suggestions on replacing the main schema id property?

**Comment by KingCosmic** [comment]
since that's generated by snapshot interpolation

**Comment by Codezilluh** [comment]
> if it is a string8 bug any suggestions on replacing the main schema id property?
>since that's generated by snapshot interpolation

I've never used the snapshot interpolation. I think that part of the schema is fine (as it will only add 6 bytes once).

You say it happens at around 120 players. With that number, you would be sending 3 megabytes of data just for the player IDs. There might be a problem in this package where it can't handle that. That is my theory. Even if that isn't the problem, it is still a good idea to limit the amount of bytes you are sending.

**Comment by KingCosmic** [comment]
yea I'm modfiying the connectionsManagers createid function to work with a random int id since a lot of my internal code relies on it. thanks for the insite, I'll close the issue if that seems to fix the problem

**Comment by Codezilluh** [comment]
I found the problem. The developer limits the ArrayBuffer to 8MB (I suppose he thought that would be enough?). I don't know why it has a hardcoded value. I'm not gonna mess with it. It would be nice to know the developers input as to why he didn't use a dynamic Buffer size. I'm also quite busy (working on my own serializing tools, shameless plug lol).

**Comment by KingCosmic** [comment]
lol so my best bet here is to compress all my data and hope i never go above 8mb in a single snapshot? @yandeu is there a reason it's hardcoded at 8mb?

@Codezilluh while im asking questions is there a way to define a array of a type like [uint64] instead of making it a object schema?

**Comment by Codezilluh** [comment]
> @Codezilluh while im asking questions is there a way to define a array of a type like [uint64] instead of making it a object schema?

Not currently. It is unfortunate because the overhead for a schema is 5 bytes. If you want, I am working on a repo called "SerializedDB" that has a schema structure similar to this. Yandeu's profile says he won't be active for a long time, so I will work on that. Currently trying to implement dynamic-length strings and integers. It's not finished but it does everything this package does so far + proper boolean implementation. It also has no overhead for schemas (if I remember my code properly).

**Comment by KingCosmic** [comment]
link me would be great to solve this quickly and if that means moving plugins I'll be happy to

**Comment by Codezilluh** [comment]
> link me would be great to solve this quickly and if that means moving plugins I'll be happy to

https://github.com/Codezilluh/SerializedDB

You can ignore the database stuff and just use the DatabaseSchema class.

**Comment by KingCosmic** [comment]
is it possible to reach you over discord incase I have any questions regarding your plugin? mine is KingCosmic#9311 incase you don't feel comfortable putting yours here.

**Comment by jeybee** [comment]
The hardcoded buffer is 8KB not MB. I hit this limit recently and altered the library locally. Here's the patch for the current NPM version that lets you specify a larger buffer size when you need it. You can apply it with [patch-package](https://www.npmjs.com/package/patch-package).

```diff
diff --git a/node_modules/@geckos.io/typed-array-buffer-schema/lib/model.d.ts b/node_modules/@geckos.io/typed-array-buffer-schema/lib/model.d.ts
index bd8c356..3370822 100644
--- a/node_modules/@geckos.io/typed-array-buffer-schema/lib/model.d.ts
+++ b/node_modules/@geckos.io/typed-array-buffer-schema/lib/model.d.ts
@@ -2,6 +2,6 @@ import { Schema } from './schema';
 import { Serialize } from './serialize';
 export declare class Model extends Serialize {
     schema: Schema;
-    constructor(schema: Schema);
+    constructor(schema: Schema, bufferSize?: number);
 }
 //# sourceMappingURL=model.d.ts.map
\ No newline at end of file
diff --git a/node_modules/@geckos.io/typed-array-buffer-schema/lib/model.js b/node_modules/@geckos.io/typed-array-buffer-schema/lib/model.js
index ad137d6..25839f2 100644
--- a/node_modules/@geckos.io/typed-array-buffer-schema/lib/model.js
+++ b/node_modules/@geckos.io/typed-array-buffer-schema/lib/model.js
@@ -3,8 +3,8 @@ Object.defineProperty(exports, "__esModule", { value: true });
 exports.Model = void 0;
 const serialize_1 = require("./serialize");
 class Model extends serialize_1.Serialize {
-    constructor(schema) {
-        super(schema);
+    constructor(schema, bufferSize=8) {
+        super(schema, bufferSize);
         this.schema = schema;
     }
 }
diff --git a/node_modules/@geckos.io/typed-array-buffer-schema/lib/serialize.d.ts b/node_modules/@geckos.io/typed-array-buffer-schema/lib/serialize.d.ts
index 00e5117..16d5112 100644
--- a/node_modules/@geckos.io/typed-array-buffer-schema/lib/serialize.d.ts
+++ b/node_modules/@geckos.io/typed-array-buffer-schema/lib/serialize.d.ts
@@ -2,9 +2,10 @@ import { Schema } from './schema';
 export declare class Serialize {
     protected schema: Schema;
     protected _buffer: ArrayBuffer;
+    protected _bufferSize: number;
     protected _dataView: DataView;
     protected _bytes: number;
-    constructor(schema: Schema);
+    constructor(schema: Schema, bufferSize: number);
     refresh(): void;
     private cropString;
     flatten(schema: any, data: any): any[];
diff --git a/node_modules/@geckos.io/typed-array-buffer-schema/lib/serialize.js b/node_modules/@geckos.io/typed-array-buffer-schema/lib/serialize.js
index 2c507d4..5fd3006 100644
--- a/node_modules/@geckos.io/typed-array-buffer-schema/lib/serialize.js
+++ b/node_modules/@geckos.io/typed-array-buffer-schema/lib/serialize.js
@@ -8,14 +8,15 @@ const lib_1 = require("./lib");
 const set_1 = __importDefault(require("lodash/set"));
 const deep_sort_object_1 = require("./deep-sort-object");
 class Serialize {
-    constructor(schema) {
+    constructor(schema, bufferSize) {
         this.schema = schema;
         this._buffer = new ArrayBuffer(0);
+        this._bufferSize = bufferSize;
         this._dataView = new DataView(this._buffer);
         this._bytes = 0;
     }
     refresh() {
-        this._buffer = new ArrayBuffer(8 * 1024);
+        this._buffer = new ArrayBuffer(this._bufferSize * 1024);
         this._dataView = new DataView(this._buffer);
         this._bytes = 0;
     }
```

**Comment by Codezilluh** [comment]
Oh yeah, I forgot about KB for a second there. It's not hard to fix, but I would rather work on my own thing without a lot of the limitations.

**Comment by yandeu** [comment]
Hi, I'm sorry I was not following this discussion. Has this been fixed? Should I merge something?

**Comment by yandeu** [comment]
@jeybee @Codezilluh What default bufferSize would be reasonable?

**Comment by jeybee** [comment]
@yandeu 8 seems fine since it’s variable and documented now.

**Comment by yandeu** [comment]
Published! Should work now.
