### ISSUE TITLE
child is wrapped in `_struct `

### ISSUE THREAD

**Issue by KuroNoDev** [geckosio/typed-array-buffer-schema#18]
Though the issue was closed, I'm still having the same issue as https://github.com/geckosio/typed-array-buffer-schema/issues/9

**Comment by yandeu** [comment]
Can you share your model with some example data?

**Comment by KuroNoDev** [comment]
something like this
```
const hero = BufferSchema.schema('heroes', {
  id,
  x: int16,
  y: int16,
  vx: int16,
  vy: int16,
  l: boolean,
  n: string8,
  a: string8,
  b: boolean,
  d: boolean,
  p: uint8,
});

const gameDataSchema = BufferSchema.schema('main', {
  heroes: [hero]
});

const snapshotSchema = BufferSchema.schema('snapshot', {
  heroes: [hero]
});
```

result looks like
```
{
  id: '',
  time: 0,
  state: {
    _struct: {
       heroes: []
    }
  }
}
```

**Comment by yandeu** [comment]
The `boolean` type does not exist. It's `bool8` or `bool16`.
`bool8` is 1 byte in size, so it is better to combine multiple boolean in one `bool8`.

Try:

```js
const hero = BufferSchema.schema('heroes', {
  x: int16,
  y: int16,
  vx: int16,
  vy: int16,
  lbd: bool8,
  n: string8,
  a: string8,
  p: uint8
})

const gameDataSchema = BufferSchema.schema('main', {
  heroes: [hero]
})

const gameState = {
  time: new Date().getTime(),
  tick: 32580,
  heroes: [{ x: 1, y: 2, vx: 3, vy: 4, lbd: [true, false, true], n: 'string8', a: 'string8', p: 1 }]
}

const mainModel = new Model(gameDataSchema)
const buffer = mainModel.toBuffer(gameState)
const data = mainModel.fromBuffer(buffer)

console.log(JSON.stringify(data, null, 2))
```
Result: 
```json
{
  "heroes": [
    {
      "a": "string8     ",
      "lbd": [
        true,
        false,
        true
      ],
      "n": "string8     ",
      "p": 5,
      "vx": 3,
      "vy": 4,
      "x": 1,
      "y": 2
    }
  ]
}
```

**Comment by KuroNoDev** [comment]
sorry the boolean was a custom type I declared 
`const boolean = { type: uint8, digits: 1 };`

that aside, I am using it with snapshot-interpolation so please try to wrap it in `state` to reproduce the issue

**Comment by yandeu** [comment]
Where in your code do you wrap it in `state`?

I don't think you can just wrap your model in a custom object. You should probably send the data and modify it after receiving.

**Comment by KuroNoDev** [comment]
The [snapshot-interpolation](https://github.com/geckosio/snapshot-interpolation) library wraps it in state, and then I convert it to buffer before sending.

**Comment by yandeu** [comment]
But, I guess, then you need to add a `state` object in your schema just like in this example:
https://github.com/geckosio/snapshot-interpolation#compression

**Comment by KuroNoDev** [comment]
hmm that's what I did. I apologize I provided wrong example on the first post. However what I did now to solve it, is to just convert the state and manually insert it into the snapshot before sending.
