### ISSUE TITLE
Not setting 'digits' on float32 adds random digits

### ISSUE THREAD

**Issue by cfortuner** [geckosio/typed-array-buffer-schema#2]
Hey! I'm not sure if this is an issue, but here is what I tried:

```
const schema = BufferSchema.schema('player', {
  b: uint8,
  n: { type: int8 },
  f: { type: float32 },
})

export const model = new Model(schema)

test('geckos', () => {
  const data = {
    b: 1,
    n: -1,
    f: 3.14,
  }
  const pkt = model.toBuffer(data)

  const out = model.fromBuffer(pkt)
  console.log(pkt.byteLength)
  console.log(out)
})

```

Outputs ->  { b: 1, n: -1, f: 3.140000104904175 }

I expected to receive 3.14 not  3.140000104904175

**Comment by cfortuner** [comment]
Another example of float32 when not using 'digits' that produced strange results

```
in: 3.1415
out: 3.1414999961853027
```

**Comment by yandeu** [comment]
This is normal. That is how floats work. Not only in JavaScript but other languages as well. I recommend using Int and 'digits' instead.

For example, for a range from 0.0000 to 6.5535, use uint16 and { digits: 4 }.

Or you could parse your float `parseFloat(3.140000104904175.toFixed(4))`
