### ISSUE TITLE
🐛 Cannot create nested schemas inside an array

### ISSUE THREAD

**Issue by reececomo** [geckosio/typed-array-buffer-schema#21]
Love the repo, thanks for adding this.

I can't seem to serialize complex data (i.e. nested multiple layers, or array inside of array).

#### Input

```json
  {
    "abc": [
      {
        "a": 2,
        "b": 3,
        "c": 4,
        "d": {
          "e": 5,
          "f": 6,
          "g": 7,
        },
      },
      {
        "a": 8,
        "b": 9,
        "c": 1,
        "d": {
          "e": 2,
          "f": 3,
          "g": 4,
        },
      }
    ],
    "def": 1
  }
```

#### Serialize / Deserialize

```ts
const layer3Schema= BufferSchema.schema('layer3', {
  e: float64,
  f: float64,
  g: uint32,
});

const layer2Schema = BufferSchema.schema('layer2', {
  a: uint32,
  b: float64,
  c: uint32,
  d: layer3Schema,
});

const layer1Schema = BufferSchema.schema('layer1', {
  abc: [layer2Schema],
  def: int8,
});

export const TestSerializer = new Model(layer1Schema);

const buffer = TestSerializer.toBuffer(input);
const output= TestSerializer.fromBuffer(buffer);

expect(output).toEqual(input);
```

#### Output

Fails to regenerate the same output as the input. The value of `output` is:

```json
  {
    "abc": [
      {
        "a": 2,
        "b": 3,
        "c": 4
      }
    ],
    "def": 1
  }
```

It appears to fail on the first `"d"` nested object, and then give up on everything else in the array.

### Use case

This is a simplified version, but our real world case is fairly similar. A state update packet (layer 1) contains multiple world state framers (layer 2), which contain information about players (layer 3) and their positions:

```typescript
{
  timestamp: 1674108312,
  frames: [
    {
      frameSeq: 45,
      players: [
        {
          id: "player-1",
          x: 45.5,
          y: 72.10003,
        },
        {
          id: "player-2",
          x: -1,
          y: 68.03444444,
        }
      ]
      // other frame properties
    },
    {
      frameSeq: 46,
      players: [
        {
          id: "player-1",
          x: 51.0,
          y: 72.10003,
        },
        {
          id: "player-2",
          x: -25.9333333,
          y: 60,
        }
      ]
      // other frame properties
    }
  ]
}
```

which incorrectly deserializes to:

```

{
  timestamp: 1674108312,
  frames: [
    {
      frameSeq: 45
    }
  ]
}
```

**Comment by reececomo** [comment]
It might be related to #9 and #18.

When I turn `frames` from an array into `frame` single object (latest frame only), the data structure deserializes back with a wrapping `_struct` nested object inside of it.

**Comment by yandeu** [comment]
Yes, looks like it only support 2 levels of nesting :/

**Comment by reececomo** [comment]
All good - I've forked [sitegui/js-binary](https://github.com/reececomo/js-binary/tree/add-32-bit-floats) (and added 32-bit floats!), and that seems to be working fairly well as an alternative 👍

**Comment by ghost** [comment]
Reece did you ever get your typescript-binary working on the client side?

**Comment by reececomo** [comment]
@Chroma72 still using that 32-bit float fork which is in JavaScript, but here is the types we're using client-side.

- https://gist.github.com/reececomo/de4c5236f9229e49811258a887beae82

**Comment by ghost** [comment]
Any chance you could open up a discussions page for your typescript-binary project? Would like to discuss further.

**Comment by reececomo** [comment]
@Chroma72 https://github.com/reececomo/js-binary/discussions

To clarify: we're not actually using the `master` branch (the experimental TS fork). We're still using the `add-32-bit-floats` branch which is in JavaScript, and providing types through the [js-binary.d.ts](https://gist.github.com/reececomo/de4c5236f9229e49811258a887beae82) file above.
