### ISSUE TITLE
How to import on the client side

### ISSUE THREAD

**Issue by bennlich** [geckosio/typed-array-buffer-schema#4]
Hiya. It looks like this module is published in commonjs format. Is there a way to import on the client-side without using a bundler? I'm currently trying to get it working with rollup, but struggling.

**Comment by bennlich** [comment]
I think the rollup issue I'm having might just be this one: https://github.com/rollup/plugins/issues/556. Not really a problem with this repo. But my solution might be to re-export as an ES module instead of commonjs.

**Comment by yandeu** [comment]
Should I create a bundle just like I did with the Snapshot Interpolation library? (https://github.com/geckosio/snapshot-interpolation/issues/5)

**Comment by bennlich** [comment]
Ya! That would be great I think.

**Comment by bennlich** [comment]
fwiw I did get the import working on the client side with rollup via the commonjs and node-resolve modules, and with esm on the node side.

**Comment by yandeu** [comment]
Glad you made it work.

I will create and publish the bundle today.
