### ISSUE TITLE
emit raw msg of different schema & model type, how to "fromBuffer" based on the buffer object source's schema model type? 

### ISSUE THREAD

**Issue by lanceTen** [geckosio/typed-array-buffer-schema#6]
Hi all,  this is my first project that requrie sending raw data.  
As normal string message, we have emit ( eventName, msg).   what is the proper way to handle the convertion of buffer data from server which are objects based on different schema & model?  

Thanks for help. 

I am using geckos raw emit method with the buffer generated from typed-array-buffer-schema module's toBuffer method

**Comment by yandeu** [comment]
I have added (https://github.com/geckosio/typed-array-buffer-schema/commit/7b252769dc6e15686f9c4e45f155ce88b8f50e35) both functions as static helper functions to the Schema class.

You will be able to do:
```ts
const bufferId = Schema.getSchemaIdFromBuffer(buffer)
const schemaId = Schema.getSchemaIdFromSchema(schema)
```

**Comment by yandeu** [comment]
I have already changed how it works. I think this is better. What do you think?

```ts
// get the schema id
const schemaId = BufferSchema.getIdFromSchema(schema)

// get the id of the top level schema (added via new Schema())
const modelId = BufferSchema.getIdFromModel(model)

// get the id of the top level schema
const bufferId = BufferSchema.getIdFromBuffer(buffer)
```

**Comment by lanceTen** [comment]
hi @yandeu ,  this looks very clear,  without any extra change or data to the schema or model.  
I really like it.  Thank you for this quick fix.

I am making a web based mmo 2d game using several popular libs, pixijs, planckjs, threadsjs, your geckosio and the typed-array-buffer-schema, etc.  I might able to contribute to your projects later when I have enough understanding. :) 

You did amazing work on this which saved me lots of time ~~
