### ISSUE TITLE
Serializing objects requires the same key order as defined in the buffer schema

### ISSUE THREAD

**Issue by DanielHZhang** [geckosio/typed-array-buffer-schema#7]
## Background

See sandbox: https://codesandbox.io/s/infallible-joliot-qhcfz?file=/src/index.ts

With the example below, serializing and deserializing an object with the same keys but different key order produces an incompatible reconstruction of the object.

```typescript
const movementSchema = BufferSchema.schema("movement", {
  sequenceNumber: uint32,
  horizontal: uint8,
  vertical: uint8
});
const movementModel = new Model(movementSchema);

const example = {
  horizontal: 4,
  vertical: 4,
  sequenceNumber: 2
};

const serialized = movementModel.toBuffer(example);
const deserialized = movementModel.fromBuffer(serialized);

console.log("Deserialized:", deserialized); 
// Expected: {sequenceNumber: 2, horizontal: 4, vertical: 4}
// But got: {sequenceNumber: 67371008, horizontal: 0, vertical: 2}
```

## Expected behaviour

The object is reconstructed properly after deserialization regardless of the key order, as long as it contains the same number of keys and same key values as defined in the schema.

**Comment by Zyie** [comment]
I have also ran into this issue. As a quick workaround I wrapped my objects around this function. Seems to work fairly well

```
export function sortKeysAlphabetically(unsorted)
{
    const sorted = Object.keys(unsorted)
        .sort()
        .reduce((acc, key) => ({
            ...acc, [key]: unsorted[key],
        }), {});

    return sorted;
}
```

but if a more permanent solution could be done that would be great

**Comment by yandeu** [comment]
I will see what I can do.
